name: Deploy Django App

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer o checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2. Configurar o Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. Configurar credenciais (garantir criação do diretório)
      - name: Configurar credenciais para o deploy
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" >> ~/id_rsa
          chmod 600 ~/id_rsa
          ssh-keyscan -H 51.210.150.116 >> ~/known_hosts

      # 5. Realizar o deploy no servidor remoto
      - name: Realizar o deploy
        run: |
          ssh -i ~/id_rsa -p 49152 ubuntu@51.210.150.116 << EOF
          # Navegar até o diretório do projeto no servidor
          cd /var/www/um-byte-de-ideias/
          
          # Atualizar o repositório
          git pull
          
          # Ativar ambiente virtual
          source .venv/bin/activate
          
          # Instalar dependências
          pip install -r requirements.txt
          
          # Aplicar migrações do Django
          python manage.py migrate
          
          # Coletar arquivos estáticos
          python manage.py collectstatic --noinput
          
          # Reiniciar o servidor (Exemplo com Gunicorn e Nginx)
          systemctl restart um-byte-de-ideias
          systemctl restart nginx
          EOF
