name: Deploy on server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy branch master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and restart the server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navegar até o diretório do projeto no servidor
            cd /var/www/um-byte-de-ideias/
            
            # Atualizar o repositório
            git pull
            
            # Ativar ambiente virtual
            source .venv/bin/activate
            
            # Instalar dependências
            pip install -r requirements.txt
            
            # Aplicar migrações do Django
            python manage.py migrate
            
            # Coletar arquivos estáticos
            python manage.py collectstatic --noinput
            
            # Reiniciar o servidor (Exemplo com Gunicorn e Nginx)
            sudo systemctl restart um-byte-de-ideias
            sudo systemctl restart nginx
